version: '3'

volumes:
  jobs_playground_local_postgres_data: {}
  jobs_playground_local_postgres_data_backups: {}
  jobs_playground_local_redis_data:
    driver: local

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: jobs_playground_local_django
    container_name: jobs_playground_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.redis
    ports:
      - '8000:8000'
    command: /bin/sh -c "while sleep 1000; do :; done"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: jobs_playground_production_postgres
    container_name: jobs_playground_local_postgres
    volumes:
      - jobs_playground_local_postgres_data:/var/lib/postgresql/data
      - jobs_playground_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
  
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - jobs_playground_local_redis_data:/data