version: '3'

volumes:
  jobs_playground_local_postgres_data: {}
  jobs_playground_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: jobs_playground_local_django
    container_name: jobs_playground_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8080:8080'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: jobs_playground_production_postgres
    container_name: jobs_playground_local_postgres
    volumes:
      - jobs_playground_local_postgres_data:/var/lib/postgresql/data
      - jobs_playground_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: jobs_playground_local_docs
    container_name: jobs_playground_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./jobs_playground:/app/jobs_playground:z
    ports:
      - '9000:9000'
    command: /start-docs
