# Generated by Django 4.2.9 on 2024-01-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-time"),
                            ("part-time", "Part-time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("unspecified", "Unspecified"),
                        ],
                        max_length=12,
                    ),
                ),
                ("description", models.TextField(max_length=10000)),
                ("posted_at", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
