# Generated by Django 4.2.9 on 2024-01-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20240129_1155"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
